### PR TITLE
align with basic knitr functionality (closes #12)

### LINKED ISSUE #12: Shaded look and feel for both code types
A quick examples with code typeset pandoc-style (ie three backtick r) looks different from knitr-typeset and eval'ed R.  Can we make both look the same?

### PR DESCRIPTION
**Pull request by eddelbuettel**

### CODE REVIEW

**Comment by coatless** [comment]
Did this regress the citations fix?

**Comment by eddelbuettel** [comment]
Huh?

**Comment by coatless** [comment]
This was introduced in #8

**Comment by coatless** [comment]
Answered my own question:

```r
base <- inherit_pdf_document(
     ..., template = template, keep_tex = keep_tex, citation_package = citation_package
)
```

The rest of the changes in the PR were sugar.

**Pull request merged**
