### PR TITLE
implemented document_date field

### PR DESCRIPTION
**Pull request by ikashnitsky**
in response to the recent discussion in #63

### CODE REVIEW

**Comment by ikashnitsky** [comment]
Maybe there should be a bit more consistency between `date_subtitle` and `document_date`. In my view their behaviour can be a bit confusing since both default to `\today`. I'd suggest to rename `date_subtitle` into `subtitle` or `infoline` – just drop date from default in this line. The date of the document can stay only in the footer – freely specified as text with the new `document_date` YAML param or resolving to `\today` by default. What do you think?

**Comment by eddelbuettel** [comment]
Can you maybe rebase to current HEAD and start over?  The fact that four files conflict is a little worrysome.  I can probably help you clean this up but not for the next few hours.

**Comment by ikashnitsky** [comment]
Damn, I'm completely lost with these git basics. The problem is that I haven't updated the pinp codebase since my last PR, and it's 34 commits behind. I haven't succeeded in rebasing it yet

**Comment by eddelbuettel** [comment]
That's ok. `git` is like magic, but takes (a lot of) practice. It helps to have colleagues or other projects that push you at times.

Can you maybe recover by hand?  I.e. save the checkout you have right now as a basis.  Also "extract" what you changes as diffs against whatever old baseline you had.  Then start over from a current checkout and happly these diffs "by hand".   

Would that be doable?

**Comment by ikashnitsky** [comment]
closing to start from scratch

**Pull request closed without merging**
