### PR TITLE
support 'headercolor' and 'linkcolor' from frontmatter

### PR DESCRIPTION
**Pull request by eddelbuettel**

### CODE REVIEW

**Comment by coatless** [comment]
Anyway we could pass the values into the `pinp.cls` file like the `footer` defines?

**Comment by eddelbuettel** [comment]
We could.  But is it really worth it?  By now `pinp.cls` is "ours" anyway and not fully self-contained.

**Comment by eddelbuettel** [comment]
Well maybe we should :)   I just tried two more "cleanups" just by renaming and dug myself a little hole. So reverted.

**Comment by eddelbuettel** [comment]
Suggest to just squash merge this and move on.  We had this (trivial) issue open for a while.

There is one issue that *would* in fact merit a release: the improved end matter.  I rendered a few package vignettes since 0.0.2, and things are better now.  Maybe that should go out into the world?

**Comment by coatless** [comment]
I'll revisit later this week to hopefully change where the declarations are.

cc #33

**Comment by eddelbuettel** [comment]
I keep thinking that a test suite would be good.  But comparing rendered pdf files (as a formal test) is not trivial / will be fragile.  People tried that with charts too.

**Comment by coatless** [comment]
@eddelbuettel see what the RStudio folks do over at:

https://github.com/rstudio/rticles/blob/master/tests/testthat/test_formats.R

**Comment by coatless** [comment]
Let's talk about this in #40

**Comment by eddelbuettel** [comment]
Yes, completion to a file is good enough.  We can do that in `tests/someSimpleScript.R` as well -- no need for extra dependencies.

**Pull request merged**
