### PR TITLE
date_subtitle -- a YAML option to have a custom string of text in subtitle

### PR DESCRIPTION
**Pull request by ikashnitsky**
instead of the default "This version was compiled on \today"

### CODE REVIEW

**Comment by ikashnitsky** [comment]
sorry, made a stupid mistake with dollar signs changing the name of the option

**Comment by coatless** [comment]
@ikashnitsky could you also add the YAML key information after the `Options` section in the vignette? 

https://github.com/eddelbuettel/pinp/blob/master/vignettes/pinp.Rmd#L157

**Comment by ikashnitsky** [comment]
@coatless ah, sorry.  I've added a bullet point in `## Document Options` in the skeleton.Rmd. Done now

**Comment by eddelbuettel** [comment]
Was about to make the same comment.  Only thing missing then is the ChangeLog but I can do that after the fact.

**Review by eddelbuettel — APPROVED** [review]
LGTM

**Comment by coatless** [comment]
In we go! Thanks @ikashnitsky

**Comment by ikashnitsky** [comment]
Thank you! The package is amazing

**Pull request merged**
