### PR TITLE
release 0.0.10

### PR DESCRIPTION
**Pull request by eddelbuettel**
Wrapping things up for a quick 0.0.10 releases around the two PRs by @ikashnitsky and myself.  Not much else changed; I simplified / shortened our affiliations to just U of I.  Ok?

### CODE REVIEW

**Comment by eddelbuettel** [comment]
Two days of "silence" on the pull request is taken as consent so onwards we move....

**Comment by coatless** [comment]
@eddelbuettel perfectly fine!

Not sure how I missed this e-mail though. I'll tweak my filters a bit more.

**Comment by eddelbuettel** [comment]
Gotcha. I use the website for notifications as the email volume (from GH alone) is too high to do something sane.

**Comment by ikashnitsky** [comment]
Hi @eddelbuettel and @coatless! Sorry I was off github recently. All fine with me. These days it was around the defense for me
https://twitter.com/ikashnitsky/status/1311671116608548865
Btw, the whole thesis is compiled using pinp. 
Huge thanks to you for this!

**Comment by eddelbuettel** [comment]
Best of luck, or as a I learned to say as a graduate student in France: _merde!_

**Comment by coatless** [comment]
@ikashnitsky congratulations! 🎉

**Comment by ikashnitsky** [comment]
Thank you!

**Pull request merged**
