### PR TITLE
add columns mode used by pandoc's :::::: and ::: blocks (closes #87)

### LINKED ISSUE #87: support multiple columns via easier pandoc notation
Both @coatless and I already know and cherish (given that we talked about it in a different context) that pandoc lets us use multiple columns in a document using `::::::` blocks with inner `:::` blocks.

But only wizard @grantmcdermott knows how to [do it _in general_ or even in _one document over html and pdf_](https://github.com/grantmcdermott/two-col-test) (giving the credit back to @yihui 's book).  

As multi-column is really good for _e.g._ code snippets, I recently "borrowed" the css trick for a html vignette I tried (with a currently less widely-used markdown wrapper) but that hit [the wall at CRAN over pandoc 2.0 lacking on Windoze](https://stat.ethz.ch/pipermail/r-package-devel/2020q3/006051.html) so I converted it to pdf.  Using this package.

Which was lacking the multi-column setup for LaTeX so I copied it into the document header, with an added `\noindent`.  That is useful, so I will add this the package now and plan to let the PR sit there for a day or so.

### PR DESCRIPTION
**Pull request by eddelbuettel**
See #87 for discussion.  Works as tested on the vignette that previously needed it in the header.

### CODE REVIEW

**Comment by coatless** [comment]
Maybe add a documentation note the `README` vignette and `pinp` layout call mentioning this is supported? 

https://github.com/eddelbuettel/pinp/blob/4fc965b9a9bd35a3899c431651de750cfe9fa7f9/vignettes/pinp.Rmd#L55-L62

https://github.com/eddelbuettel/pinp/blob/4fc965b9a9bd35a3899c431651de750cfe9fa7f9/R/pinp.R#L68-L71

**Comment by eddelbuettel** [comment]
Could do but not urgent and can be done later. It's _optional_ anyway at the `pandoc` level.  Just that before the additional it broke :crying_cat_face: and now it no longer does.

It also very much does _not_ need a YAML option.  Hence "maybe not".

**Comment by eddelbuettel** [comment]
The other issue for 'maybe not' is that the side-by-side view of code .... pretty much needs one-column mode which does not fit into our default vignette (as easily).  We could try to prove a point and have two columns side-by-side _inside one column_ but it likely going to be awkward.

Your reminder about documenting options is good though.

**Comment by eddelbuettel** [comment]
For completeness, I tried it.  Outer `\begin{widetext} ... \end{widetext}` then clashes with the width setting `pandoc` supports. Switching with `\onecolumn` and back to `\twocolumn` works, but forces a pagebreak.   So not really a candidate for our default vignette.

**Pull request merged**
